### ISSUE TITLE
Project lacks build instructions

### ISSUE THREAD

**Issue by ahcox** [dnl-blkv/mcdowell-cv#8]
The obvious `pdflatex McDowell_CV_Template.tex` produces the following:

    Fatal fontspec error: "cannot-use-pdftex"
    ...

`xelatex McDowell_CV_Template.tex` produces the following:

    ! Package microtype Error: Letterspacing currently doesn't work with xetex
    ...

`lualatex McDowell_CV_Template.tex` seems to work. If this is the correct invocation, it should be prominent in the readme.

**Comment by dnl-blkv** [comment]
@ahcox thank you for raising the issue. If you read the first line of the readme, you will clearly see that this class is 

> LuaLaTeX class

Thus, I am not sure why `pdflatex McDowell_CV_Template.tex` is obvious to you. Nevertheless, I will add `lualatex McDowell_CV_Template.tex` to make it even more clear.

**Comment by dnl-blkv** [comment]
Fixed
